/* data.js — Selected works + research (real project imagery)
   Exports CG_PROJECTS, CG_RESEARCH on window.

   NOTE ON METADATA: per brief, each project carries only LOCATION and PROGRAM.
   Descriptions are the author's project texts in the house style. */

const CG_PROJECTS = [
  {
    id: "community-centre-mixed-uses",
    index: "01",
    title: "Community Centre of Mixed Uses",
    location: "Merlo, GBA, ARG.",
    program: ["Education, Civic & Culture"],
    images: [
      "img/01 Community Centre of Mixed Uses.jpg",
      "img/02 Community Centre of Mixed Uses.jpg",
      "img/03 Community Centre of Mixed Uses.jpg",
      "img/04 Community Centre of Mixed Uses.jpg",
      "img/05 Community Centre of Mixed Uses.jpg",
      "img/06 Community Centre of Mixed Uses.jpg",
      "img/07 Community Centre of Mixed Uses.jpg",
      "img/08 Community Centre of Mixed Uses.jpg",
      "img/09 Community Centre of Mixed Uses.jpg",
      "img/10 Community Centre of Mixed Uses.jpg"
    ],
    description: [
      "Situated between consolidated urban fabric and a natural stream, the project establishes a civic structure that restores continuity between city and landscape.",
      "Rather than operating as an autonomous object, the building acts as a permeable spatial system that activates the existing void and generates a sequence of collective grounds. Three landscape conditions — community, temporary and productive — are embedded within the architectural strategy, extending public life beyond the built envelope.",
      "Access is articulated through two differentiated thresholds: a double-height civic entrance oriented toward the water and a more contained entry aligned with the urban grid.",
      "A central void organises the programme and environmental performance of the building, calibrating spatial hierarchy between the public hall and the smaller educational and cultural units.",
      "The proposal transforms a marginal urban edge into an active civic interface, positioning architecture as an instrument for collective engagement."
    ]
  },
  {
    id: "masterplan-catalinas-norte",
    index: "02",
    title: "Masterplan Catalinas Norte",
    location: "Catalinas Norte, CABA, ARG.",
    program: ["Urban Design"],
    images: [
      "img/01 Masterplan Catalinas Norte.jpg",
      "img/02 Masterplan Catalinas Norte.jpg",
      "img/03 Masterplan Catalinas Norte.jpg",
      "img/04 Masterplan Catalinas Norte.jpg"
    ],
    description: [
      "Catalinas Norte, a riverfront office district in Retiro, experienced a progressive loss of urban vitality following the transformation of workplace dynamics. The proposal reconceives the area as a mixed-use urban field capable of sustaining continuous public activity.",
      "Ground occupation and built density are restructured to prioritise permeability and pedestrian intensity. A new transversal network reconnects the site to both city and waterfront, dissolving the barriers generated by elevated podiums and defensive boundaries.",
      "Activated base levels and sunken courtyards redefine the ground plane, introducing human scale while intensifying interaction. Commercial programmes occupy the lower levels, while educational, cultural, health and leisure uses establish a vertical layering of activity.",
      "Rather than a formal redesign, the intervention operates as a strategic reconfiguration, transforming a fragmented corporate enclave into a cohesive civic landscape."
    ]
  },
  {
    id: "innovation-campus",
    index: "03",
    title: "Innovation Campus",
    location: "Catalinas Norte, CABA, ARG.",
    program: ["Mixed Use & Adaptive Reuse"],
    images: [
      "img/01 Innovation Campus.jpg",
      "img/02 Innovation Campus.jpg",
      "img/03 Innovation Campus.jpg",
      "img/04 Innovation Campus.jpg",
      "img/05 Innovation Campus.jpg",
      "img/06 Innovation Campus.jpg"
    ],
    description: [
      "Originally conceived as a mono-functional office tower (1976–1980), the building had gradually lost relevance within the evolving urban context. The project redefines the existing structure as an Innovation Campus, introducing programmatic diversity within its original framework.",
      "The intervention is based on targeted subtraction and reconfiguration of the ground plane. New transversal connections and carved courtyards restore permeability and establish a renewed relationship between interior space and public realm.",
      "The base becomes a porous civic interface, while upper levels accommodate educational, cultural, health and leisure programmes, generating a vertically integrated mixed-use environment within the existing structural grid.",
      "Through adaptive reuse, the proposal converts a closed corporate object into a dynamic and socially activated vertical campus."
    ]
  },
  {
    id: "hybrid-library",
    index: "04",
    title: "Hybrid Library",
    location: "Villa Riachuelo, CABA, ARG.",
    program: ["Education & Culture"],
    images: [
      "img/01 Hybrid Library OK.jpg",
      "img/02 Hybrid Library.jpg",
      "img/03 Hybrid Library.jpg",
      "img/04 Hybrid Library.jpg",
      "img/05 Hybrid Library.jpg"
    ],
    description: [
      "Located within an educational block defined by a school and a church, the project reinterprets the library as an extension of public space rather than an isolated institution.",
      "A longitudinal pedestrian passage crossing the site becomes the generative element of the proposal. Its deviation toward the corner establishes diagonal spatial flows that restructure the relationship between school, church and neighbourhood. As it traverses the building, the path consolidates at its core, structuring circulation and spatial continuity.",
      "The permeable ground floor accommodates two distinct domains: an independently accessed library with controlled circulation and a flexible cultural area open to the community. Reading rooms occupy the upper levels, ensuring spatial concentration and acoustic clarity.",
      "A microperforated metal envelope recomposes the volume and regulates light, transforming natural illumination into a spatial medium that reveals the layered interior landscape.",
      "The library emerges as a civic connector where movement, light and programme converge to redefine the contemporary educational threshold."
    ]
  },
  {
    id: "national-university-arts",
    index: "05",
    title: "National University of the Arts",
    location: "Puerto Madero, CABA, ARG.",
    program: ["Education"],
    images: [
      "img/01 National University of the Arts.jpg",
      "img/02 National University of the Arts.jpg",
      "img/03 National University of the Arts.jpg",
      "img/04 National University of the Arts.jpg",
      "img/05 National University of the Arts.jpg",
      "img/06 National University of the Arts.jpg",
      "img/07 National University of the Arts.jpg",
      "img/08 National University of the Arts.jpg"
    ],
    description: [
      "Strategically positioned between Puerto Madero and the historic city centre, the project establishes a new institutional presence within a transitional urban context.",
      "A transversal campus strategy organises the site, structuring the building perpendicular to its axis and generating two complementary spatial conditions: a dense urban forest and a linear system of academic sheds. Built form and landscape are inseparable components of a continuous spatial and environmental system.",
      "The ground floor is conceived as a continuous public plane, accommodating the auditorium, foyer, dining hall and student centre, all extending beneath a shaded arcade formed by the upper volumes.",
      "Above, a monolithic concrete mass is selectively perforated to establish visual and environmental continuity. These voids function as extensions of the classrooms, encouraging informal exchange and collective interaction.",
      "Suspended bridges and a longitudinal stair structure the interior as a vertical field of movement, transforming circulation into a central architectural experience.",
      "The university is conceived as an open institutional framework where mass and void, structure and landscape, support artistic production and shared cultural life."
    ]
  }
];

// Research — featured items, an extension of the design process (not a blog).
const CG_RESEARCH = {
  intro: "Research is treated as an extension of the design process — a way of testing ideas about territory, reuse and material alongside building. The work below records that thinking.",
  items: [
    {
      id: "designing-responsibly-foster",
      index: "01",
      title: "Designing Responsibly: Insights from Nicola Scaranaro, Partner at Foster + Partners",
      meta: "Article · Interview",
      location: "YACademy Student Magazine",
      cover: "img/Foster 00.jpg",
      images: ["img/Foster 01 copia.jpg", "img/Foster 02 copia.jpg"],
      description: [
        "Interview and editorial contribution for the YACademy Student Magazine, exploring innovation, sustainability and technology-driven design strategies in contemporary architectural practice."
      ],
      sections: [
        {
          paragraphs: [
            "[[How can architects design for a future in which cultures, climates, and technologies evolve faster than ever?]] It is a question that resonates strongly today, especially when considering how architecture can connect places, communities, and long-term environmental responsibility. It becomes even more relevant when exploring how global innovation, local identity, and ecological intelligence can coexist within contemporary design practice.",
            "A conversation with Nicola Scaranaro, Partner at Foster + Partners, offered a clear perspective on this balance. His reflections highlighted three essential dimensions: the value of cultural research, the irreplaceable role of human insight, and the responsibility architects hold in the ecological transition."
          ]
        },
        {
          heading: "Innovation through cultural understanding",
          paragraphs: [
            "For Scaranaro, every project begins long before any line is drawn. The preliminary phase, including research, attentive listening, and cultural interpretation, is crucial to ensure that global innovation does not overshadow local identity. Foster + Partners approaches this balance through multidisciplinary teams in which architects, environmental specialists, and even anthropologists work together to deeply understand places and the people who inhabit them.",
            "Vernacular knowledge, he notes, is an irreplaceable point of departure. In climatically demanding contexts, understanding how oases work, how shade is formed, or how wind circulates, becomes essential for developing contemporary strategies that do not imitate tradition, but reinterpret it. By merging cultural analysis with advanced environmental modelling, the firm aims to craft spaces that are not only more comfortable and high-performing, but also deeply responsive to their context."
          ]
        },
        {
          heading: "Technology as a tool",
          paragraphs: [
            "When asked what technology should never replace, Scaranaro was clear: architecture remains “humans designing for humans.” While tools like prefabrication, modular systems, environmental simulations, and AI accelerate iteration and optimize resources, they cannot substitute the designer’s critical, ethical, and empathetic perspective.",
            "For him, technology is most valuable when it supports better building practices, reducing waste, improving control, and enhancing performance. But even in an increasingly digitized workflow, human sensitivity remains central: understanding how a space is lived, the kind of experience it generates, and how it becomes part of someone’s memory, something that technology can never replicate."
          ]
        },
        {
          heading: "Architecture’s ecological responsibility",
          paragraphs: [
            "Scaranaro frames the ecological transition around a foundational question: What does each project contribute to the city, the community, and the world? Addressing this question requires architects to consider, from the earliest stages, the embodied carbon of materials and construction systems, the possibility of reusing or adapting existing structures before contemplating demolition, and the need for programmatic flexibility so that buildings can evolve over time.",
            "It also demands a commitment to circularity by designing structures that can be dismantled, reused, or reconfigured, and to continuous environmental measurement supported by digital and AI tools. Designing with a long-term life-cycle perspective, whether 50 or 100 years, is for Scaranaro not only good practice but an ethical obligation, one that defines the architect’s role in shaping a more responsible built environment."
          ]
        },
        {
          heading: "Looking ahead",
          paragraphs: [
            "Nicola Scaranaro’s insights offer a clear reading of where architecture is heading. The discipline’s future will be shaped not only by technological capacity, but by its ability to remain conscious, adaptable, and rooted in cultural and environmental responsibility. Innovation and sensitivity, far from being opposites, are mutually reinforcing forces that can help build more humane and resilient cities.",
            "For today’s emerging architects, his message stands as a valuable reminder: design with intelligence and humility; work with digital tools in ways that preserve the human dimension of design; and maintain a global outlook balanced by a deep respect for the local."
          ]
        }
      ]
    },
    {
      id: "high-training-hospitality",
      index: "02",
      title: "High Training Course in Architecture for Hospitality",
      meta: "Postgraduate Course",
      location: "YACademy, Bologna, Italy",
      cover: "img/YACADEMY.jpg",
      images: [
        "img/High Training Course in Architecture for Hospitality 01 copia.jpg",
        "img/High Training Course in Architecture for Hospitality 02 copia.jpg",
        "img/High Training Course in Architecture for Hospitality 03 copia.jpg",
        "img/High Training Course in Architecture for Hospitality 04 copia.jpg",
        "img/High Training Course in Architecture for Hospitality 05 copia.jpg",
        "img/High Training Course in Architecture for Hospitality 06 copia.jpg",
        "img/High Training Course in Architecture for Hospitality 07 copia.jpg",
        "img/High Training Course in Architecture for Hospitality 08 copia.jpg",
        "img/High Training Course in Architecture for Hospitality 09 copia.jpg"
      ],
      description: [
        "An intensive postgraduate program dedicated to contemporary hospitality architecture, combining theoretical research, site exploration and design practice within an international and multidisciplinary environment.",
        "The course brought together architects, designers and tutors from diverse cultural and professional backgrounds, creating a dynamic setting for collaboration, critical discussion and knowledge exchange. Working alongside highly motivated peers and leading professionals provided a valuable opportunity to broaden my perspective on design and strengthen my professional ambitions.",
        "A key component of the program was the field trip to Vulcano Island in the Aeolian archipelago, followed by an advanced design workshop supervised by Anteo Taro Boschi Sanada, Partner at Kengo Kuma & Associates (KKA). The workshop focused on the adaptive reuse of the historic Gelso Lighthouse, exploring its transformation into a hospitality destination while preserving its cultural identity and relationship with the surrounding landscape.",
        "This experience reinforced my interest in hospitality design and deepened my understanding of architecture's capacity to generate new forms of inhabitation through the careful reinterpretation of pre-existing structures, landscapes and histories."
      ]
    },
    {
      id: "international-urban-design-workshop",
      index: "03",
      title: "International Urban Design Workshop",
      meta: "Workshop",
      location: "University of Buenos Aires (FADU) and National University of Colombia",
      cover: "img/Workshop FADU 00.jpg",
      images: [
        "img/Workshop FADU 01.jpg",
        "img/Workshop FADU 02.jpg",
        "img/Workshop FADU 03.jpg",
        "img/Workshop FADU 04.jpg",
        "img/Workshop FADU 05.jpg",
        "img/Workshop FADU 06.jpg",
        "img/Workshop FADU 07.jpg"
      ],
      sections: [
        {
          heading: "Buenos Aires",
          question: "How can an urban area with a centripetal tendency reverse its destiny and become an integrative scenario through which connections with its surrounding territory are strengthened, while developing a social field supported by sustainable agricultural production infrastructure?",
          paragraphs: [
            "Through the analysis of a 500-hectare sector in Merlo, along the Presidente Perón Highway corridor, the project investigated the relationship between urban residue, metropolitan capital and an imploding urban grid.",
            "The area was understood as a large urban piece tending towards increasing spatial and social isolation, yet containing the potential to become a new point of connection. The research explored how a centripetal urban condition could be reversed through the creation of an integrative landscape infrastructure, strengthening connections with its surroundings while supporting new forms of social interaction and agricultural production."
          ]
        },
        {
          heading: "Bogotá",
          question: "How can a space alter existing conditions and become an urban connector capable of balancing two different social realities?",
          paragraphs: [
            "This research focused on a 500-hectare site along the northern section of the ALO corridor in Bogotá. Defined by urban residue, collective production systems and a series of infrastructural barriers, the area is characterised by a large vacant space enclosed by major mobility networks.",
            "The project explored the potential of this void to operate as an urban connector, capable of bridging contrasting social conditions and transforming a fragmented territory into a more integrated and accessible urban landscape."
          ]
        }
      ]
    }
  ]
};

window.CG_PROJECTS = CG_PROJECTS;
window.CG_RESEARCH = CG_RESEARCH;
